Update Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml

diff --git a/.github/workflows/Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml b/.github/workflows/Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml
--- a/.github/workflows/Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml
+++ b/.github/workflows/Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml
@@ -161,18 +161,36 @@ jobs:
           echo "Kernel compilation failed"
           exit 1
         fi
-    - name: Compile packages
+    - name: Compile core packages
+      id: compile_core_packages
+      run: |
+        cd openwrt
+        sex -x
+        echo "Starting core packages compilation at $(date)"
+        free -h
+        LOG_FILE="packages.log"
+        ERROR_PATTERN="error|failed|undefined reference|cannot"
+        MAX_RETRY=6
+        retry_count=0  
+        {make package/feeds/base/compile -j2 V=s > core_packages.log 2>&1} || {make package/feeds/base/compile -j1 V=s > core_packages.log 2>&1} || {
+          echo "Core packages compilation failed, printing last 100 lines:"
+          tail -n 100 core_packages.log
+          exit 1
+        }
+        echo "Core packages compiled successfully at $(date)"
+        
+    - name: Compile Remaining packages
       id: compile_packages
       run: |
         cd openwrt
-        #set -o pipefail
+        sex -x
         LOG_FILE="packages.log"
         ERROR_PATTERN="error|failed|undefined reference|cannot"
         # 编译并记录日志
         MAX_RETRY=6
         retry_count=0                    
         while [ $retry_count -lt $MAX_RETRY ]; do
-                          make -j1 package/compile V=s > packages.log 2>&1 || {
+                          {make package/feeds/base/compile -j2 V=s > core_packages.log 2>&1} || {make -j1 package/compile V=s > packages.log 2>&1 && break }|| {
                           retry_count=$((retry_count + 1))
                           echo "尝试第 $retry_count 次修复..."
                           if grep -q "PKG_VERSION.*error" packages.log; then
