Update Build_OpenWRT.org_1_for_XIAOMI_R4.yml

diff --git a/.github/workflows/Build_OpenWRT.org_1_for_XIAOMI_R4.yml b/.github/workflows/Build_OpenWRT.org_1_for_XIAOMI_R4.yml
--- a/.github/workflows/Build_OpenWRT.org_1_for_XIAOMI_R4.yml
+++ b/.github/workflows/Build_OpenWRT.org_1_for_XIAOMI_R4.yml
@@ -151,7 +151,7 @@ jobs:
           cd openwrt
           cp ../compile_with_retry.sh .
           echo "开始尝试编译packages" 
-          bash compile_with_retry.sh "make -j1 V=s" "packages.log" 6 "error:|failed|undefined reference" || exit 1
+          bash compile_with_retry.sh "make -j1 V=s" "packages.log" 6 "error:|failed|undefined reference" || || { make -j1 packages/compile V=s > packages.log 2>&1 && tail -300 packages.log}        
 
 
       
@@ -177,7 +177,7 @@ jobs:
             tail -300 kernel.log           
           elif [ "${{ steps.compile_packages.outcome }}" = "failure" ]; then             
             echo "Compile packages failed. Showing last 300 lines of packages.log:"             
-            tail -300 packages.log || { make -j1 packages/compile V=s > packages.log 2>&1 && tail -300 packages.log}         
+            tail -300 packages.log  
           elif [ "${{ steps.build_image.outcome }}" = "failure" ]; then             
             echo "Build image failed. Showing last 300 lines of image.log:"             
             tail -300 image.log           
