Update Build_coolsnowwolf-LEDE_for_XIAOMI_R4-full.yml

diff --git a/.github/workflows/Build_coolsnowwolf-LEDE_for_XIAOMI_R4-full.yml b/.github/workflows/Build_coolsnowwolf-LEDE_for_XIAOMI_R4-full.yml
--- a/.github/workflows/Build_coolsnowwolf-LEDE_for_XIAOMI_R4-full.yml
+++ b/.github/workflows/Build_coolsnowwolf-LEDE_for_XIAOMI_R4-full.yml
@@ -212,15 +212,15 @@ jobs:
         cd openwrt
         echo "根据https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=1086753&pid=11643216，首次编译时，容易报错：bash: po2lmo: command not found 这应该是因为编译XXXXXXX需要把 luci-base 先编译出来，但是目前顺序可能是先编译了 hello world 导致出现问题，此时使用 make package/feeds/luci/luci-base/compile V=99 编译出 luci-base 后再编译就不会报错。 这个问题虽然出现的频率不高，但是也不低 "
         make -j$(nproc) package/feeds/luci/luci-base/compile V=s || make -j1 package/feeds/luci/luci-base/compile V=s
-        make package/feeds/routing/batman-adv/compile > batman.log 2>&1 || {
+        make -j1 V=s package/feeds/routing/batman-adv/compile > batman.log 2>&1 || {
           echo "编译batman-adv失败，查看日志报错处的前50行到后20行"
           grep -B20 -A50 'FAILED' batman.log
-          echo "batman_first_fail=true" >> $GITHUB_ENV
+          echo "batman_first_fail=true" >> $GITHUB_OUTPUT
         }
         
     - name: Try compiling batman-adv
       id: compile_batman_2
-      if: env.batman_first_fail == 'true'
+      if: steps.compile_batman_1.outputs.batman_first_fail == 'true'
       run: |
         cd openwrt
         set -x
