Update Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml

diff --git a/.github/workflows/Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml b/.github/workflows/Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml
--- a/.github/workflows/Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml
+++ b/.github/workflows/Build_Lienol_OpenWrt_1_for_XIAOMI_R4.yml
@@ -341,16 +341,16 @@ jobs:
             echo "尝试第 $retry_count 次修复..."
           done 
 
-      - name: Debug directory contents
-        run: |
-          ls -lR openwrt/build_dir
-          ls -lR openwrt/staging_dir
-          ls -l openwrt/.config || echo ".config not found"
-          
-      - name: Upload build artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: Lienol-first-build
-          path: |
-            openwrt
+    - name: Debug directory contents
+      run: |
+        ls -lR openwrt/build_dir
+        ls -lR openwrt/staging_dir
+        ls -l openwrt/.config || echo ".config not found"
+        
+    - name: Upload build artifacts
+      uses: actions/upload-artifact@v4
+      with:
+        name: Lienol-first-build
+        path: |
+          openwrt
 
