Update SimpleBuildOpenWRT_Official.yml

diff --git a/.github/workflows/SimpleBuildOpenWRT_Official.yml b/.github/workflows/SimpleBuildOpenWRT_Official.yml
--- a/.github/workflows/SimpleBuildOpenWRT_Official.yml
+++ b/.github/workflows/SimpleBuildOpenWRT_Official.yml
@@ -46,47 +46,30 @@ jobs:
           sudo apt update
           sudo apt install -y build-essential musl-tools libncurses5-dev libncursesw5-dev gawk git libssl-dev gettext zlib1g-dev swig rsync ruby unzip libpam0g-dev libcurl4-openssl-dev libdeflate-dev
           pip install requests jq beautifulsoup4 || pip3 install requests jq beautifulsoup4
-
+          
+      - name: Load custom feeds
+        run: |
+          [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
+          chmod +x $DIY_P1_SH
+          cd openwrt
+          $GITHUB_WORKSPACE/$DIY_P1_SH
+          
       - name: Update feeds
         run: |
           cd openwrt
-          echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall' >>feeds.conf.default
-          echo 'src-git OpenClash https://github.com/vernesong/OpenClash' >>feeds.conf.default
-          echo 'src-git small8 https://github.com/kenzok8/small-package' >>feeds.conf.default
           ./scripts/feeds update -a
           ./scripts/feeds install -a
           cp ../config_for_OpenWrt_org .config
           make defconfig
           echo "在defconfig之后查看配置文件"
           cat .config | grep CONFIG_TARGET_.*=y
-          sed -i \
-              -e '/select PACKAGE_trojan-plus/d' \
-              -e '/config PACKAGE_.*_INCLUDE_Trojan_Plus/,/default /s/default y/default n/' \
-              feeds/passwall/luci-app-passwall/Makefile || true
-          
-          sed -i \
-              -e '/select PACKAGE_trojan-plus/d' \
-              -e '/config PACKAGE_.*_INCLUDE_Trojan_Plus/,/default /s/default y/default n/' \
-              package/feeds/passwall/luci-app-passwall/Makefile || true
-              
-          sed -i \
-              -e '/select PACKAGE_trojan-plus/d' \
-              -e '/config PACKAGE_.*_INCLUDE_Trojan_Plus/,/default /s/default y/default n/' \
-              feeds/small8/luci-app-passwall/Makefile || true
-          sed -i \
-              -e '/select PACKAGE_trojan-plus/d' \
-              -e '/config PACKAGE_.*_INCLUDE_Trojan_Plus/,/default /s/default y/default n/' \
-              package/feeds/small8/luci-app-passwall/Makefile || true
-
-          sed -i '/^ *DEPENDS:=/ s/$/ +libudebug/' package/network/config/netifd/Makefile || true
-          sed -i '/^ *CMAKE_OPTIONS/s/$/ -DENABLE_UDDEBUG=OFF/' package/network/config/netifd/Makefile || sed -i '/^define Package\/netifd/a\ \ \ CMAKE_OPTIONS += -DENABLE_UDDEBUG=OFF' package/network/config/netifd/Makefile || true
-
+      
           
       - name: Download package
         id: download_package
         run: |
           cd openwrt
-          make download -j2
+          make download -j4
           find dl -size -1024c -exec ls -l {} \;
           find dl -size -1024c -exec rm -f {} \;     
 
@@ -125,24 +108,24 @@ jobs:
           limit-access-to-actor: false
           timeout-minutes: 300
           
-      - name: Compile packages
-        id: compile_packages
-        run: |
-          cd openwrt
-          echo "尝试编译 dnsmasq 及其常见依赖，看具体是哪个环节出错"
-          make package/libs/ubus/compile V=s || echo "ubus compile failed"
-          make package/system/uci/compile V=s || echo "uci compile failed"
-          make package/network/config/libnl-tiny/compile V=s || echo "libnl-tiny compile failed" # dnsmasq 可能依赖
-          make package/network/services/dnsmasq/compile V=s -j1 # 单线程编译 dnsmasq，看详细错误
-          cp ../compile_with_retry.py .
-          # echo "先尝试编译容易失败的lua-neturl"
-          # cp ../compile_with_retry.py . && python compile_with_retry.py "make -j1 package/feeds/small8/lua-neturl/compile V=s" "packages.log" 8
-          #echo "先尝试编译容易失败的trojan-plus"
-          #python compile_with_retry.py "make -j1 package/feeds/small8/trojan-plus/compile V=s" "packages.log" 6
-          echo "开始尝试编译所有packages" 
-          # cp ../compile_with_retry.sh . && bash compile_with_retry.sh "make -j1 package/compile V=s" "packages.log" 8 
-          #cp ../compile_with_retry.py .
-          python compile_with_retry.py "make -j1 package/compile V=s" "packages.log" 
+      # - name: Compile packages
+      #   id: compile_packages
+      #   run: |
+      #     cd openwrt
+      #     echo "尝试编译 dnsmasq 及其常见依赖，看具体是哪个环节出错"
+      #     make package/libs/ubus/compile V=s || echo "ubus compile failed"
+      #     make package/system/uci/compile V=s || echo "uci compile failed"
+      #     make package/network/config/libnl-tiny/compile V=s || echo "libnl-tiny compile failed" # dnsmasq 可能依赖
+      #     make package/network/services/dnsmasq/compile V=s -j1 # 单线程编译 dnsmasq，看详细错误
+      #     cp ../compile_with_retry.py .
+      #     # echo "先尝试编译容易失败的lua-neturl"
+      #     # cp ../compile_with_retry.py . && python compile_with_retry.py "make -j1 package/feeds/small8/lua-neturl/compile V=s" "packages.log" 8
+      #     #echo "先尝试编译容易失败的trojan-plus"
+      #     #python compile_with_retry.py "make -j1 package/feeds/small8/trojan-plus/compile V=s" "packages.log" 6
+      #     echo "开始尝试编译所有packages" 
+      #     # cp ../compile_with_retry.sh . && bash compile_with_retry.sh "make -j1 package/compile V=s" "packages.log" 8 
+      #     #cp ../compile_with_retry.py .
+      #     python compile_with_retry.py "make -j1 package/compile V=s" "packages.log" 
           
 
 
@@ -154,32 +137,10 @@ jobs:
           LOG_FILE="image.log"
           # cp ../compile_with_retry.sh . && bash compile_with_retry.sh "make -j1 V=s" "image.log" 7 
           # cp ../compile_with_retry.py . 
-          make -j2 V=s || python compile_with_retry.py "make -j2 V=s" "image.log"  || python compile_with_retry.py "make -j1 V=s" "image.log" 
+          #make -j2 V=s || python compile_with_retry.py "make -j2 V=s" "image.log"  || python compile_with_retry.py "make -j1 V=s" "image.log" 
+          make -j2 V=s || make package/feeds/packages/kmod/clean V=s && make -j1 V=s
 
           
-          
-      - name: 查看日志结尾300行
-        if: always()
-        run: |
-          cd openwrt
-          if [ "${{ steps.compile_tools.outcome }}" = "failure" ]; then             
-            echo "Compile tools failed. Showing last 300 lines of tools.log:"             
-            tail -300 tools.log           
-          elif [ "${{ steps.compile_toolchain.outcome }}" = "failure" ]; then             
-            echo "Compile toolchain failed. Showing last 300 lines of toolchain.log:"             
-            tail -300 toolchain.log           
-          elif [ "${{ steps.compile_kernel.outcome }}" = "failure" ]; then             
-            echo "Compile kernel failed. Showing last 300 lines of kernel.log:"             
-            tail -300 kernel.log           
-          elif [ "${{ steps.compile_packages.outcome }}" = "failure" ]; then             
-            echo "编译packages失败，查看日志结尾300 lines of packages.log:"             
-            tail -300 packages.log     
-          elif [ "${{ steps.build_image.outcome }}" = "failure" ]; then             
-            echo "Build image failed. Showing last 300 lines of image.log:"             
-            tail -300 image.log           
-          else             
-            echo "All steps completed successfully. No log to show."           
-          fi 
           
       - name: Set environment variables
         id: setEnv
